version: "3"

services:
  abra:
    build: ..
    ports:
      - "80:80"
    volumes:
      - ./var/www/html
    networks:
    - abc

  db:
    image: postgres:12.1
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
    networks:
      - abc

  adminer:
    image: adminer:4.7.5
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - abc

volumes:
  volume1:

networks:
  abc:
    driver: bridge

